# Commands to start on workspace startup
tasks:
  - init: cd ticket-frontend && npm install && npm install -g @angular/cli
    command: ng serve -o
# Ports to expose on workspace startup
ports:
  - port: 4200
    onOpen: open-preview
